### ISSUE TITLE
How Create new tables?

### ISSUE THREAD

**Issue by raisiqueira** [awurth/slim-rest-base#3]
Hi! First congratulations for the project.
I would like to know how do I create new tables in the database. Can I use the same console?

**Comment by awurth** [comment]
Hi. Database related files are located in the `bootstrap/database/` folder. To create new tables, I suggest you look into the `auth.php` file where I'm creating the tables for the authentication feature.
You can put your new tables in it or create a new file (and add it to `index.php`) and create tables with eloquent's `Manager::schema()->create();` method. Don't forget to add the created tables in `drop.php` to remove them before creating them.
To run the script, just run `php console db` in a terminal

For more information about creating tables with eloquent, you can check the documentation:
https://laravel.com/docs/5.4/migrations#creating-tables
