### ISSUE TITLE
Proposal: ORM to test

### ISSUE THREAD

**Issue by francescobianco** [awurth/slim-rest-base#4]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by awurth** [comment]
Hi. The project uses Sentinel for authentication which is only compatible with Eloquent ORM so I would have to create a custom authentication system, but I don't really have time for that as I'm working on other projects.

But there is no reason your library can't be integrated with Slim.
